site_name: Syntha SDK Documentation
site_description: Context-Based Multi-Agent Framework
site_url: https://docs.syntha.ai
repo_url: https://github.com/syntha/syntha-sdk
repo_name: syntha/syntha-sdk

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Core Concepts: core-concepts.md
  - Installation: installation.md
  - API Reference:
    - Overview: api/overview.md
    - ContextMesh: api/context-mesh.md
    - Tools: api/tools.md
    - Prompts: api/prompts.md
    - Persistence: api/persistence.md
    - Tool Schemas: api/schemas.md
  - Guides:
    - Overview: guides/overview.md
    - Basics: guides/basics.md
    - Context Management: guides/context.md
    - Tools & Permissions: guides/tools.md
    - Final Remarks: guides/final-remarks.md 